services:
  auth:
    build: .
    container_name: auth-service
    expose:
      - "8100"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./keys:/app/keys
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    restart: unless-stopped
    mem_limit: 256m
    networks:
      - nano-banana-network
      - postgres_default
      - middleware_default
      - ai-audio-network

networks:
  nano-banana-network:
    external: true
  postgres_default:
    external: true
  middleware_default:
    external: true
  ai-audio-network:
    external: true
