name: Deploy to Dev Server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ~/project/auth-service
          git fetch origin
          git reset --hard origin/main
          git clean -fd
          docker compose up -d --build
          docker image prune -f
